# Generated by Django 5.0.6 on 2024-05-16 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmapp', '0002_directory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directory',
            old_name='City',
            new_name='city',
        ),
    ]
